### ISSUE TITLE
Get the center coordinates of the detected object

### ISSUE THREAD

**Issue by Pateman16** [dmalyuta/apriltags2_ros#2]
Is it possible to get the center coordinates of the detected object somehow with this code?
Im getting the relative position to the object by subscribing to the /tag_detections-topic from the camera but I need to move my robot to objects center somehow?

**Comment by dmalyuta** [comment]
Do you mean the center coordinates in the image (i.e. in pixel coordinates)? If so, this is not implemented currently. Feel free to modify the code and submit a pull request.
