### ISSUE TITLE
Subscribing information in the /tag_detections topic

### ISSUE THREAD

**Issue by lalal321** [dmalyuta/apriltags2_ros#25]
Hello, I want to get the information about  geometry_msgs/PoseWithCovarianceStamped pose  in the topic /tag_detections, but subscribing pulished topic /tag_detections, /tag_detections/detections could not find the valid information, what should I do to get the pose information ? Thank you.

**Comment by manomitbal** [comment]
You will have to `#include <apriltags2_ros/AprilTagDetectionArray.h>` add this line to your code where you are invoking your call back and then access the `const apriltags2_ros::AprilTagDetectionArray::ConstPtr& msg` message type as provided by the library to access the pose. You will have to include "apriltags2" in your CMakelists and package.xml.
