### ISSUE TITLE
Adding branches!

### ISSUE THREAD

**Issue by davelkan** [dmalyuta/apriltags2_ros#26]
Ok this isn't an issue but i'd like to push some changes to a cpp_beta branch but don't have permissions. Can you add an additional branch or enable others to do so? @dmalyuta

**Comment by dmalyuta** [comment]
@davelkan I sent you an invite to become a collaborator. I'm sorry for not having the time to respond to all your (awesome) contributions and bug reports. I hope this way you can have more freedom to positively expand the project.

**Comment by davelkan** [comment]
Thanks! I'm getting an internal review of some of my changes and will be pushing my beta branch for others to test soon
