### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by csukuangfj** [dmalyuta/apriltags2_ros#29]
See the code
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/apriltag.c#L1190
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/apriltag.c#L1488

The following statement overwrites the previously detected results which loses them forever
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2_ros/src/common_functions.cpp#L197

Furthermore, it uses
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2_ros/src/common_functions.cpp#L153
to destroy the detections in the destructor, which is **incorrect** and results in again memory leak.
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/include/common/zarray.h#L76-L85

https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/include/apriltag.h#L238
**H** is not freed! See the code below

https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/apriltag.c#L1039
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/include/common/matd.h#L333-L334

**Comment by wxmerkt** [comment]
Now merged, thank you very much for spotting and providing a fix :).
